version: "3.7"

services:
  examapp_mongo:
    container_name: examapp_mongo
    image: mongo
    restart: always
    ports:
      - 27017:27018
  app:
    container_name: examapp
    restart: always
    build: .
    env_file: .env
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    ports:
      - 8081:80
    external_links:
      - examapp_mongo
    depends_on:
      - examapp_mongo
