version: "3.7"

services:
  examapp_mongo:
    container_name: examapp_mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017
  app:
    container_name: examapp
    restart: always
    volumes:
      - ./src:/usr/src
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.local
    environment:
      - PORT=${PORT}
      - HTTPSPORT=${HTTPSPORT}
      - MONGO_URL=${MONGO_URL}
      - NODE_ENV=development
    ports:
      - 8082:8081
      - 8443:8443
      - 9229:9229
    links:
      - examapp_mongo
    depends_on:
      - examapp_mongo

volumes:
  mongo-data:
    driver: local
