version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  app:
    container_name: node
    restart: always
    volumes:
      - ./src:/usr/src
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.local
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
      - NODE_ENV=development
    ports:
      - 8081:8081
      - 9229:9229
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
