version: "3.7"

services:
  examapp_mongo:
    container_name: examapp_mongo
    image: mongo
    command: --quiet --logpath /dev/null
  app:
    container_name: examapp
    external_links:
      - examapp_mongo
    depends_on:
      - examapp_mongo
